#!/usr/bin/env node
// Generates the Announcements journey screens (screens/ann-*.json) for the "Announcements WIP" page. Re-run after editing: node ds/files/announcements/gen.mjs
import { writeFileSync } from "node:fs";
const PIN = { ds: "ds/files/announcements", page: "13157:51469", section: "13149:51550", height: 900 };
const T = (i, content, style, color, x = {}) => ({ t: "text", i, content, style, color, ...x });
const row = (i, children, x = {}) => ({ t: "row", i, children, ...x }), col = (i, children, x = {}) => ({ t: "stack", i, children, ...x });
const nav = { c: "main-nav", i: "nav", p: { types: "collapsed" }, fill: "y" };
const crumb = (a, b) => ({ t: "row", i: "topbar", fill: "x", h: 40, align: "center", children: [{ c: "es-breadcrumb", i: "crumb", fill: "x", p: { Variant: "with Icon", Actions: "false", "AI assist button": "false", "Avatar Group": "false" }, text: [a, b], bg: "none" }] });
const btn = (i, label, o = {}) => ({ c: o.brand ? "button-brand" : "button-neutral", i, p: { Size: o.size || "md", Hierarchy: o.h || (o.brand ? "Primary" : "Secondary"), "Icon leading": o.icon ? "true" : "false", ...(o.icon ? { "Icon leading swap": o.icon } : {}), "Icon trailing": "false", ...(o.state ? { State: o.state } : {}) }, text: { Button: label }, ...(o.x || {}) });
const pic = (seed, w, h) => `https://picsum.photos/seed/${seed}/${w * 2}/${h * 2}.jpg`; // real pictures from picsum (seeded = stable); keyword search is not offered by picsum
const imgBox = (i, w, h, x = {}) => ({ t: "stack", i, ...(w ? { w } : { fill: "x" }), h, ...(x.img ? {} : { bg: "bg-tertiary" }), radius: "xl", border: "border-secondary", why: "photo placeholder — images are not drawn by Clause", children: [], ...x });
const AUTHOR = row("author", [{ c: "avatar", i: "au-av", p: { Size: "xxs", Type: "Letter", Colour: "Brand Solid" }, text: ["A"] }, T("au-t", "Aaryak Garg · Today", "Text xs/Regular", "text-tertiary")], { gap: "md", align: "center" });
const TITLE = "Join us at Customer Day on 16 October";
const section = (i, h, items) => col(i, [T(i + "-h", h, "Text sm/Semibold", "text-primary"), ...items.map((t, k) => row(i + "-r" + k, [T(i + "-d" + k, "•", "Text sm/Regular", "text-secondary"), T(i + "-t" + k, t, "Text sm/Regular", "text-secondary", { grow: true })], { gap: "md" }))], { gap: "md", fill: "x" });

// ---------- shared pieces
const qa = (k, q, a) => col("qa" + k, [T("q" + k, q, "Text xs/Regular", "text-tertiary"), T("a" + k, a, "Text sm/Regular", "text-primary")], { gap: "xxs", fill: "x" });
const choices = col("choices", [qa(1, "What would you like to announce?", "Invite people to an event"), qa(2, "Which event is it?", "Customer Day in London"), qa(3, "Who should see this?", "Everyone at UnifyApps"), qa(4, "How long should it stay up?", "1 week")], { fill: "x", gap: "lg", pad: "xl", border: "border-secondary", radius: "2xl" });
const bubble = row("user-row", [col("user-bubble", [T("user-t", "Create a new Announcement", "Text sm/Regular", "text-primary")], { bg: "bg-tertiary", radius: "2xl", px: "xl", py: "md" })], { fill: "x", justify: "end" });
const artifact = (v, draft) => ({ c: "inline-artifact-cards", i: "art", p: { State: "DOC" }, text: [TITLE, "Announcement • " + v + (draft ? " • Draft" : ""), "Preview"], fill: "x" });
const input = { c: "copilot-desktop-input-box", i: "input", p: { Type: "Bottom small", State: "Default", "Tools & Sources": "No", Text: "Placeholder", Attachment: "No", "Inline Skills": "false" }, fill: "x", text: ["Ask for a change, or select words in the preview"] };
function chat({ v = "v1", draft = true, edited = null, extra = [], suggestions = ["Try a different cover", "Make it shorter", "Add a line on why this matters"], bottom = input }) {
  return col("chat", [
    col("thread", [bubble, choices, row("thoughts-row", [{ c: "agent-avatar", i: "th-av", p: { Size: "xs", Type: "Advance" } }, { c: "thoughts", i: "thoughts", p: { State: "Closed" } }], { gap: "md", align: "center" }), artifact(v, draft),
      T("lead", "Here’s a first draft, open on the right as readers will see it. Type straight into it, or select words and tell me how to change them.", "Text sm/Regular", "text-primary", { fill: "x" }),
      col("facts", ["For: everyone at UnifyApps, from when you publish until Wed 14 Oct", "Sections: The day, What to do, Questions?", "Cover: A speaker on stage in front of a full room"].map((t, k) => row("f" + k, [T("fb" + k, "•", "Text sm/Regular", "text-secondary"), T("ft" + k, t, "Text sm/Regular", "text-secondary", { grow: true })], { gap: "md" })), { gap: "xs", fill: "x" }),
      ...(suggestions ? [{ c: "suggested-prompts", i: "sugg", p: { Type: "Lines" }, text: suggestions, fill: "x" }] : []), ...extra,
      ...(edited ? [row("edited", [{ c: "tag", i: "edited-tag", p: { Icon: "False", Action: "Text only", Size: "sm", Type: "Outline", State: "Default" }, text: [edited + " · " + v] }], { fill: "x", justify: "end" })] : [])], { gap: "xl", fill: "x", grow: true }),
    bottom], { w: 560, fill: "y", gap: "xl", px: "xl", pb: "xl", pt: "md" });
}
function preview({ v = "v1", cover = "img", loading = false, publishDisabled = false, overlay = [] }) {
  const body = loading ? col("skeleton", [0, 1, 2, 3, 4, 5, 6].map(k => imgBox("sk" + k, k % 3 === 2 ? 320 : 0, 12, { radius: "full", border: undefined, bg: "bg-tertiary" })), { gap: "lg", fill: "x" })
    : col("doc", [
      T("p-title", TITLE, "Display sm/Regular", "text-primary", { fill: "x" }), AUTHOR,
      cover === "img" ? imgBox("cover", 0, 184, { img: pic("customer-day-stage", 734, 184) }) : cover === "none" ? { t: "row", i: "cover-empty", fill: "x", h: 56, align: "center", justify: "center", gap: "md", radius: "xl", border: "border-secondary", dash: true, children: [{ c: "icon-upload-cloud", i: "ce-ic", w: 16, h: 16 }, T("ce-t", "Add a cover", "Text sm/Medium", "text-primary"), T("ce-s", "or ask in the chat", "Text sm/Regular", "text-tertiary")] } : imgBox("cover", 0, 184, { img: pic("customer-day-stage", 734, 184) }),
      T("p-b1", "Customer Day is on Thursday 16 October at the London office, and every seller is invited. It’s a full day with the customers who shape our roadmap, and the best chance this year to hear, in their own words, why they chose us.", "Text sm/Regular", "text-secondary", { fill: "x" }),
      section("s1", "The day", ["10:00 — Welcome, and what customers asked us for this year", "11:30 — Customer panel with Lowe’s, Greif and Cority", "14:00 — Small-group sessions by industry", "17:00 — Drinks on the 19th floor"]),
      section("s2", "What to do", ["Register by Friday 3 October, so we can plan seats and lunch", "Bring one customer story from this quarter, two minutes long", "Can’t come in person? The panel is streamed on Teams"]),
      col("s3", [T("s3-h", "Questions?", "Text sm/Semibold", "text-primary"), T("s3-t", "Ask Sales Enablement in #customer-day, and we’ll answer within a day.", "Text sm/Regular", "text-secondary", { fill: "x" })], { gap: "md", fill: "x" }),
      col("ask", [{ c: "suggested-prompts", i: "ask-sugg", p: { Type: "Lines" }, text: ["When do I need to register?", "Who is on the customer panel?", "Can I join on Teams?"], fill: "x" }], { gap: "md", fill: "x", pt: "xl" })], { gap: "xl", fill: "x" });
  return col("preview", [
    { c: "arifact-header", i: "pv-head", fill: "x", text: [TITLE], ops: [{ nodes: ["Frame 2147266824", "Frame 2147266884", "Frame 2147266889"].map(name => ({ name, hide: true })) }] },
    col("pv-body", [body], { fill: "x", grow: true, px: "5xl", pt: "3xl", pb: "xl", bg: "bg-primary" }), ...overlay], { grow: true, fill: "y", bg: "bg-primary", border: "border-secondary", radius: "xl", clip: true });
}
const screen = (name, title, children, extra = []) => ({ title, ...PIN, tree: { t: "row", i: "root", gap: "none", clip: true, children: [nav, col("main", [crumb("Announcements", "New announcement"), row("split", children, { fill: "x", grow: true, gap: "none", pr: "md", pb: "md" })], { grow: true, fill: "y", gap: "none", bg: "bg-secondary" }), ...extra] } });
const out = {};

// 2 draft ready
out["ann-2-draft-ready"] = screen("2", "Announcement — draft ready", [chat({}), preview({})]);
// 3 cover hover toolbar
out["ann-3-cover-hover"] = screen("3", "Announcement — cover hover", [chat({}), preview({})], [row("cover-bar", [btn("cb1", "Change cover", { size: "xs", h: "Tertiary" }), btn("cb2", "Reposition", { size: "xs", h: "Tertiary" }), btn("cb3", "Remove", { size: "xs", h: "Tertiary" })], { gap: "xxs", pad: "xxs", bg: "bg-primary", radius: "lg", border: "border-secondary", abs: { x: 1086, y: 218 }, why: "toolbar floats on the cover's top-right on hover" })]);
// 4 gallery
const smallTabs = (i, texts, sel, hideN = 0) => ({ c: "small-tabs", i, text: texts, ops: [{ nodes: [...Array.from({ length: hideN }, (_, k) => ({ name: "Tab", nth: 5 - hideN + k, hide: true })), ...texts.map((_, k) => ({ name: "Tab", nth: k, props: { Current: k === sel ? "True" : "False" } }))] }] });
const tabs4 = (sel) => smallTabs("tabs", ["Gallery", "Upload", "Link", "Unsplash"], sel, 1);
const tiles = col("tiles", [0, 1].map(r => row("tr" + r, [0, 1, 2, 3].map(k => imgBox("tile" + r + k, 83, 56, { radius: "lg", img: pic("cover-" + (r * 4 + k), 83, 56) })), { gap: "md" })), { gap: "md" });
out["ann-4-cover-gallery"] = screen("4", "Announcement — change cover (gallery)", [chat({}), preview({})], [col("popover", [row("po-head", [tabs4(0), T("po-rm", "Remove", "Text xs/Regular", "text-tertiary")], { fill: "x", justify: "between", align: "center" }), T("po-lbl", "UnifyApps", "Text xs/Regular", "text-tertiary"), tiles, { c: "tag", i: "fits", p: { Icon: "False", Action: "Text only", Size: "xs", Type: "Blue", State: "Default" }, text: ["Fits your words"], abs: { x: 24, y: 90 }, why: "badge on the first suggested cover, relative to the popover" }], { w: 400, gap: "lg", pad: "xl", bg: "bg-primary", border: "border-secondary", radius: "xl", abs: { x: 692, y: 236 }, why: "popover anchored under the cover toolbar" })]);
// 5 link
// 4b upload (missing screen from the reference journey)
out["ann-4b-cover-upload"] = screen("4b", "Announcement — change cover (upload)", [chat({}), preview({})], [col("popover", [row("po-head", [tabs4(1), T("po-rm", "Remove", "Text xs/Regular", "text-tertiary")], { fill: "x", justify: "between", align: "center" }), { c: "file-upload-empty-state", i: "po-drop", fill: "x", p: { "File drag and drop": "true", State: "Default", Size: "xl" }, text: ["Upload a file", "or paste a picture with ⌘V", "Wide pictures, at least 1500 pixels across, look best."] }], { w: 400, gap: "lg", pad: "xl", bg: "bg-primary", border: "border-secondary", radius: "xl", abs: { x: 692, y: 236 }, why: "popover anchored under the cover toolbar" })]);
out["ann-5-cover-link"] = screen("5", "Announcement — change cover (link)", [chat({}), preview({})], [col("popover", [row("po-head", [tabs4(2), T("po-rm", "Remove", "Text xs/Regular", "text-tertiary")], { fill: "x", justify: "between", align: "center" }), row("po-in", [{ c: "input-field-outline", i: "link-in", fill: "x", p: { Size: "sm", Type: "Default", Label: "false", "Hint text": "false", "Help icon": "false", "Leading icon": "false", Encryption: "false", Destructive: "False", State: "Placeholder" }, text: ["Paste a link to a picture"] }, btn("use", "Use as cover", { brand: true, size: "sm" })], { fill: "x", gap: "md", align: "center" }), T("po-h", "Works with any picture on the web.", "Text xs/Regular", "text-tertiary")], { w: 400, gap: "lg", pad: "xl", bg: "bg-primary", border: "border-secondary", radius: "xl", abs: { x: 692, y: 236 }, why: "popover anchored under the cover toolbar" })]);
// 6 no cover / edited
out["ann-6-no-cover"] = screen("6", "Announcement — no cover (edited v2)", [chat({ v: "v2", draft: false, edited: "You edited it", suggestions: ["Add a cover picture", "Make it shorter", "Add a line on why this matters"] }), preview({ v: "v2", cover: "none" })]);
// 7 publish confirm
const modal = (i, rows, alertTxt, ok, errText) => [col("scrim", [], { w: 1440, h: 900, bg: "bg-base-dark", opacity: 0.35, abs: { x: 0, y: 0 }, why: "dim the page behind the dialog" }), col(i, [
  { c: "modal-header", i: "mh", p: { "X close button": "true", Tabs: "false", Type: "Subtext Single line", Size: "sm", back: "no" }, text: ["Publish this announcement?", "It goes live right away — you can unpublish any time."], fill: "x" },
  col("rows", rows, { fill: "x", gap: "md", px: "xl", pb: "xl" }),
  ...(alertTxt ? [col("al-wrap", [{ c: "alert", i: "al", p: { Size: "sm", Color: errText ? "Error" : "Brand", Actions: "false", "Supporting text": "false", "Title Text": "true", Icon: "true", "Double Stack": "Off" }, text: [alertTxt], fill: "x" }], { fill: "x", px: "xl", pb: "xl" })] : []),
  { c: "modal-actions", i: "ma", p: { Checkbox: "false", "Tertiary button": "false", Type: "Horizontal right aligned (checkbox)", Size: "sm", Destructive: "False" }, text: ["Cancel", ok], fill: "x" }], { w: 480, gap: "none", bg: "bg-primary", radius: "3xl", border: "border-secondary", abs: { x: 480, y: 250 }, why: "dialog centred on the page" })];
const li = (i, t, s, ic, st) => ({ c: "list-item-cardified", i, fill: "x", p: { Size: "md", Type: "Icon simple", Icon: "true", "Supporting Text": "false", Subtext: "true", Badge: "false", Actions: "false", "Action Buttons": "false", ...(st ? { State: st } : {}) }, text: [t, s], ops: [{ nodes: [{ name: "Featured Icon_Solid", nth: 0, icon: ic }] }] });
const kv = (i, k, v, last, muted) => row(i, [T(i + "-k", k, "Text sm/Regular", "text-tertiary", { w: 116 }), T(i + "-v", v, "Text sm/Medium", muted ? "text-tertiary" : "text-primary", { grow: true }), { c: "icon-chevron-right", i: i + "-c", w: 16, h: 16 }], { fill: "x", gap: "lg", align: "center", px: "xl", py: "lg", ...(last ? {} : { borderB: "border-secondary" }) });
const pubPop = (rows, blockedTxt) => [col("popover", [T("pp-t", "Publish to home pages", "Text md/Medium", "text-primary"), col("pp-rows", rows, { fill: "x", gap: "none", border: "border-secondary", radius: "xl" }), ...(blockedTxt ? [{ c: "alert", i: "al", p: { Size: "sm", Color: "Error", Actions: "false", "Supporting text": "false", "Title Text": "true", Icon: "true", "Double Stack": "Off" }, text: [blockedTxt], fill: "x" }] : []), row("pp-act", [btn("pp-cancel", "Cancel", { size: "md" }), btn("pp-go", "Publish now", { brand: true, size: "md", state: blockedTxt ? "Disabled" : undefined })], { gap: "md", justify: "end", fill: "x" })], { w: 408, gap: "xl", pad: "xl", bg: "bg-primary", border: "border-secondary", radius: "2xl", abs: { x: 1008, y: 76 }, why: "popover anchored under the Publish button, right-aligned to the preview" })];
out["ann-7-publish-confirm"] = screen("7", "Announcement — publish confirm", [chat({}), preview({})], pubPop([kv("k1", "Who sees it", "Everyone at UnifyApps", false), kv("k2", "When it shows", "Now until Wed 14 Oct", true)]));
// 8 published
out["ann-8-published"] = screen("8", "Announcement — published", [chat({ v: "v2", draft: false, edited: "Published" }), preview({ v: "v2", cover: "img" })], [{ c: "alert", i: "toast", p: { Size: "md", Color: "Success", Actions: "true", "Supporting text": "true", "Title Text": "true", Icon: "true", "Double Stack": "Off" }, text: ["Published — live for 320 people until Wed 14 Oct", "Dismiss", "View on home"], w: 560, abs: { x: 880, y: 830 }, why: "toast at the top centre after publishing" }]);
// 12 validation
out["ann-12-publish-blocked"] = screen("12", "Announcement — publish blocked", [chat({}), preview({})], pubPop([kv("k1", "Who sees it", "Not set", false, true), kv("k2", "When it shows", "Now until Wed 14 Oct", true)], "Choose who should see this before publishing."));
// 10 generating
out["ann-10-generating"] = screen("10", "Announcement — generating draft", [col("chat", [col("thread", [bubble, choices, row("thoughts-row", [{ c: "agent-avatar", i: "th-av", p: { Size: "xs", Type: "Advance" } }, { c: "thoughts", i: "thoughts", p: { State: "Open" } }], { gap: "md", align: "center" }), ...["Reading Customer Day in your calendar", "Checking who is in Everyone at UnifyApps", "Writing the first draft"].map((t, k) => row("st" + k, [{ c: "icon-clock", i: "st-ic" + k, w: 16, h: 16 }, T("st-t" + k, t, "Text sm/Regular", "text-tertiary")], { gap: "md", align: "center", pl: "xl" }))], { gap: "xl", fill: "x", grow: true }), { ...input, p: { ...input.p, State: "Generating" } }], { w: 560, fill: "y", gap: "xl", px: "xl", pb: "xl", pt: "md" }), preview({ loading: true, publishDisabled: true })]);
// 11 error
out["ann-11-generation-failed"] = screen("11", "Announcement — draft failed", [col("chat", [col("thread", [bubble, choices, T("fail-t", "I couldn’t write the draft this time — nothing was saved. Try again, or change one of your answers.", "Text sm/Regular", "text-primary", { fill: "x" }), row("fail-a", [btn("retry", "Try again", { brand: true, size: "sm" }), btn("change", "Change answers", { size: "sm" })], { gap: "md" })], { gap: "xl", fill: "x", grow: true }), input], { w: 560, fill: "y", gap: "xl", px: "xl", pb: "xl", pt: "md" }), col("preview", [col("empty", [{ c: "alert", i: "err", p: { Size: "md", Color: "Error", Actions: "true", "Supporting text": "true", "Title Text": "true", Icon: "true", "Double Stack": "Off" }, text: ["Couldn’t write the draft", "Dismiss", "Try again"], fill: "x" }], { fill: "x", px: "xl", pt: "xl" })], { grow: true, fill: "y", bg: "bg-primary", border: "border-secondary", radius: "xl" })]);
// 9 list
const pill = (i, s) => ({ t: "row", i, w: 140, align: "center", children: [{ c: "pill-squared", i: i + "-p", p: { Size: "sm", Type: "Pill Clear", Icon: "Dot", Color: s === "Live" ? "Success" : s === "Scheduled" ? "Brand" : s === "Expired" ? "Warning" : "Gray" }, text: [s] }] });
const cell = (i, t, w) => ({ c: "table-cell", i, p: { Style: "Text", Lead: "No", State: "Default", Size: "md", "Supporting Text": "false", Badge: "false", Dropdown: "false" }, text: [t], ...(w ? { w } : { fill: "x" }) });
const hdr = (i, t, w) => ({ c: "col-header-cell", i, p: { Size: "md", Text: "True", Checkbox: "False", State: "Default", "Data Icon": "Off" }, text: [t], bg: "none", ...(w ? { w } : { fill: "x" }) });
const rows = [["Join us at Customer Day on 16 October", "Everyone · 320 people", "Live", "Wed 14 Oct"], ["Q4 town hall — submit your questions", "Everyone · 320 people", "Live", "Fri 17 Oct"], ["New expense policy from 1 November", "Finance · 42 people", "Scheduled", "Sat 1 Nov"], ["Office closed for Diwali", "London office · 410 people", "Scheduled", "Mon 20 Oct"], ["Security training is due this week", "Engineering · 610 people", "Draft", "—"], ["Welcome to the new Sales leaders", "Sales · 320 people", "Expired", "Fri 3 Oct"]];
const trow = (r, k) => row("tr" + k, [cell("c1-" + k, r[0]), cell("c2-" + k, r[1], 220), pill("st-" + k, r[2]), cell("c4-" + k, r[3], 120), row("ac" + k, [{ c: "small-icon-button", i: "mo" + k, p: { Size: "sm", "Icon swap": "@icon-dots-horizontal" } }], { w: 56, justify: "center" })], { fill: "x", h: 48, align: "center", borderB: "border-secondary" });
out["ann-9-list"] = { title: "Announcements — list", ...PIN, tree: { t: "row", i: "root", gap: "none", clip: true, children: [nav, col("main", [crumb("Announcements", "All announcements"), col("content", [row("head", [T("h1", "Announcements", "Display md/Regular", "text-primary"), btn("new", "New announcement", { brand: true, icon: "@icon-plus" })], { fill: "x", justify: "between", align: "center" }), smallTabs("tabs", ["All", "Live", "Scheduled", "Drafts", "Expired"], 0), col("table", [row("thead", [hdr("h-a", "TITLE"), hdr("h-b", "AUDIENCE", 220), hdr("h-c", "STATUS", 140), hdr("h-d", "ENDS", 120), row("h-e", [], { w: 56 })], { fill: "x", h: 44, align: "center", borderB: "border-secondary" }), ...rows.map(trow)], { fill: "x", gap: "none" })], { w: 960, gap: "3xl", pt: "5xl" })], { grow: true, fill: "y", gap: "none", bg: "bg-primary", align: "center" })] } };

for (const [n, s] of Object.entries(out)) writeFileSync(`screens/${n}.json`, JSON.stringify(s, null, 1));
console.log(Object.keys(out).join("\n"));
