#!/usr/bin/env node
// build-plugin.mjs — generates figma-plugin/{manifest.json,code.js,ui.html}.
//   Silent by default: the UI iframe is hidden, updates are pushed by the server over SSE, errors surface as a Figma toast.
//   Clause Assist — pieces live in scripts/plugin/ (annotate-glue.js, ui.html). Menu: Start (silent) · Open Clause Assist. "Start (silent)" · "Show panel" (same plugin, visible status panel + HTML drop zone).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dir = resolve(root, "figma-plugin");
mkdirSync(dir, { recursive: true });
const runtime = readFileSync(resolve(root, "scripts/runtime.js"), "utf8");
const extract = readFileSync(resolve(root, "scripts/extract.js"), "utf8");
const annGlue = readFileSync(resolve(root, "scripts/plugin/annotate-glue.js"), "utf8");
const dsExtractSrc = readFileSync(resolve(root, "scripts/plugin/extract-ds.js"), "utf8");
const PORT = process.env.PORT || 8787;
const ui = readFileSync(resolve(root, "scripts/plugin/ui.html"), "utf8").replace(/__PORT__/g, String(PORT));

writeFileSync(resolve(dir, "manifest.json"), JSON.stringify({
  name: "Clause Assist",
  id: "es-ds-live-preview-dev",
  api: "1.0.0",
  main: "code.js",
  ui: "ui.html",
  editorType: ["figma"],
  documentAccess: "dynamic-page",
  permissions: ["teamlibrary"],
  menu: [{ name: "Start (silent)", command: "start" }, { name: "Open Clause Assist", command: "panel" }, { name: "Extract components & tokens", command: "extract" }],
  networkAccess: { allowedDomains: ["none"], devAllowedDomains: [`http://localhost:${PORT}`] },
}, null, 2));

writeFileSync(resolve(dir, "code.js"), `// generated by scripts/build-plugin.mjs — do not edit
figma.showUI(__html__, { width: 320, height: 520, visible: figma.command === "panel" || figma.command === "extract" });
figma.ui.postMessage({ type: "cmd", command: figma.command });


${annGlue}
${dsExtractSrc}

const AF = Object.getPrototypeOf(async function () {}).constructor;
let CACHE = {}, CACHE_HASH = null, exTimer = null;

figma.ui.onmessage = async (msg) => {
  if (await annMessage(msg)) return;
  if (msg.type === "notify") { figma.notify(msg.text, { error: !!msg.error, timeout: msg.error ? 6000 : 1500 }); return; }
  if (msg.type === "ds-extract") {
    const T0 = Date.now(); const say = t => figma.ui.postMessage({ type: "ds-progress", text: t });
    try { const r = await dsExtract({ ignoreSections: msg.ignoreSections || [] }, (part, data) => figma.ui.postMessage({ type: "ds-part", part, data }), say); figma.ui.postMessage({ type: "ds-done", result: r, ms: Date.now() - T0 }); }
    catch (e) { figma.ui.postMessage({ type: "ds-done", error: String((e && e.message) || e) }); }
    return;
  }
  if (msg.type === "resize") { figma.ui.resize(msg.w, msg.h); return; }
  if (msg.type !== "build") return;
  if (msg.rtHash !== CACHE_HASH) { CACHE = {}; CACHE_HASH = msg.rtHash; }
  clearTimeout(exTimer);
  const S = msg.screen;
  const t0 = Date.now();
  let page = null, before = new Set();
  try {
    page = await figma.getNodeByIdAsync(S.PAGE_ID);
    if (!page) throw new Error("canvas page " + S.PAGE_ID + " not found in this file (" + figma.root.name + ") — open the Enterprise Brain Base file");
    await figma.setCurrentPageAsync(page);
    before = new Set(page.children.map(n => n.id));
    const old = page.children.filter(n => n.getPluginData("es-screen") === msg.name);
    if (old.length) { S.POS = { x: Math.min(...old.map(o => o.x)), y: old[0].y }; for (const o of old) o.remove(); }
    let fn = null;
    if (msg.runtime) { try { fn = new AF("figma", "SCREEN", "CACHE", msg.runtime); } catch (e) { fn = null; } }
    const res = fn ? await fn(figma, S, CACHE) : await runScreen(S);
    for (const id of res.roots) { const n = await figma.getNodeByIdAsync(id); if (n) n.setPluginData("es-screen", msg.name); }
    res.ms = Date.now() - t0;
    figma.ui.postMessage({ type: "result", ok: true, name: msg.name, res });
    // HTML export: wait until saves go quiet, then extract once
    exTimer = setTimeout(async () => {
      try {
        const ex = msg.extract
          ? await new AF("figma", "ROOTS", "SCENE", "CACHE", msg.extract + "\\nreturn await extractDom(ROOTS, SCENE, CACHE);")(figma, res.roots, S, CACHE)
          : await extractDom(res.roots, S, CACHE);
        figma.ui.postMessage({ type: "dom", name: msg.name, scene: S, screens: ex.screens, warnings: ex.warnings });
      } catch (e) { figma.ui.postMessage({ type: "domerror", name: msg.name, error: String((e && e.message) || e) }); }
    }, 1200);
  } catch (e) {
    let error = String((e && e.message) || e);
    if (page) for (const n of [...page.children]) if (!before.has(n.id)) n.remove();
    if (/variable|style|component/i.test(error)) {
      try {
        const cols = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync();
        error += " | file: " + figma.root.name + " | libs: " + [...new Set(cols.map(c => c.libraryName))].join(", ") + " (" + cols.length + " collections)";
      } catch (e2) { error += " | file: " + figma.root.name + " | teamLibrary: " + ((e2 && e2.message) || e2); }
    }
    figma.notify("Clause: " + error.slice(0, 180), { error: true, timeout: 6000 });
    figma.ui.postMessage({ type: "result", ok: false, name: msg.name, error });
  }
};
`);

writeFileSync(resolve(dir, "ui.html"), ui);
console.error("→ figma-plugin/{manifest.json,code.js,ui.html}");
