#!/usr/bin/env node
// build-plugin.mjs — generates figma-plugin/{manifest.json,code.js,ui.html}.
//   Silent by default: the UI iframe is hidden, updates are pushed by the server over SSE, errors surface as a Figma toast.
//   Clause Assist — pieces live in scripts/plugin/ (annotate-glue.js, ui.html). Menu: Start (silent) · Open Clause Assist. "Start (silent)" · "Show panel" (same plugin, visible status panel + HTML drop zone).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dir = resolve(root, "figma-plugin");
mkdirSync(dir, { recursive: true });
const runtime = readFileSync(resolve(root, "scripts/runtime.js"), "utf8");
const extract = readFileSync(resolve(root, "scripts/extract.js"), "utf8");
const annGlue = readFileSync(resolve(root, "scripts/plugin/annotate-glue.js"), "utf8");
const dsExtractSrc = readFileSync(resolve(root, "scripts/plugin/extract-ds.js"), "utf8");
const PORT = process.env.PORT || 8787;
const ui = readFileSync(resolve(root, "scripts/plugin/ui.html"), "utf8").replace(/__PORT__/g, String(PORT));

writeFileSync(resolve(dir, "manifest.json"), JSON.stringify({
  name: "Clause Assist",
  id: "es-ds-live-preview-dev",
  api: "1.0.0",
  main: "code.js",
  ui: "ui.html",
  editorType: ["figma"],
  documentAccess: "dynamic-page",
  permissions: ["teamlibrary"],
  menu: [{ name: "Open Clause Assist", command: "panel" }, { name: "Start (silent)", command: "start" }, { name: "Extract components & tokens", command: "extract" }],
  networkAccess: { allowedDomains: ["none"], devAllowedDomains: [`http://localhost:${PORT}`] },
}, null, 2));

writeFileSync(resolve(dir, "code.js"), `// generated by scripts/build-plugin.mjs — do not edit
figma.showUI(__html__, { width: 320, height: 520, visible: figma.command === "panel" || figma.command === "extract" });
figma.ui.postMessage({ type: "cmd", command: figma.command });


${annGlue}
${dsExtractSrc}

const AF = Object.getPrototypeOf(async function () {}).constructor;
let CACHE = {}, CACHE_HASH = null, exTimer = null; let UI_SIZE = { w: 320, h: 520 }; const PAGE_OF = {}, RT_FN = { hash: null, fn: null }; // screen name → page id (skips the all-pages walk on rebuilds)

figma.ui.onmessage = async (msg) => {
  if (await annMessage(msg)) return;
  if (msg.type === "notify") { figma.notify(msg.text, { error: !!msg.error, timeout: msg.error ? 6000 : 1500 }); return; }
  if (msg.type === "ds-extract") {
    const T0 = Date.now(); const say = t => figma.ui.postMessage({ type: "ds-progress", text: t });
    try { const r = await dsExtract({ ignoreSections: msg.ignoreSections || [] }, (part, data) => figma.ui.postMessage({ type: "ds-part", part, data }), say); figma.ui.postMessage({ type: "ds-done", result: r, ms: Date.now() - T0 }); }
    catch (e) { figma.ui.postMessage({ type: "ds-done", error: String((e && e.message) || e) }); }
    return;
  }
  if (msg.type === "goto") {
    try { const pg = await figma.getNodeByIdAsync(msg.pageId); if (pg) await figma.setCurrentPageAsync(pg); const n = msg.nodeId ? await figma.getNodeByIdAsync(msg.nodeId) : null; if (n) { figma.currentPage.selection = [n]; figma.viewport.scrollAndZoomIntoView([n]); } } catch (e) {}
    return;
  }
  if (msg.type === "resize") {
    // reposition() takes CANVAS coordinates while the window size is in screen px (measured: windowSpace = origin + zoom × canvas).
    // So: read the window position, resize (anchors top-left), then move by the size delta converted px → canvas units (÷ zoom); verify and correct once.
    const w = Math.round(msg.w), h = Math.round(msg.h), cw = UI_SIZE.w, ch = UI_SIZE.h;
    const getPos = async () => { try { const p = await figma.ui.getPosition(); return p && p.windowSpace && p.canvasSpace ? { wx: p.windowSpace.x, wy: p.windowSpace.y, cx: p.canvasSpace.x, cy: p.canvasSpace.y } : null; } catch (e) { return null; } };
    const before = msg.anchor === "br" ? await getPos() : null;
    figma.ui.resize(w, h); UI_SIZE = { w, h };
    if (before) {
      const z = figma.viewport.zoom || 1, dbg = { z, before, cw, ch, w, h };
      // anchor the bottom-right corner, then clamp the window inside the visible canvas (never over the side panels)
      const vb = figma.viewport.bounds, M = 12;
      const toWx = c => before.wx + z * (c - before.cx), toWy = c => before.wy + z * (c - before.cy);
      const vl = toWx(vb.x), vr = toWx(vb.x + vb.width), vt = toWy(vb.y), vbm = toWy(vb.y + vb.height);
      let wantWx = before.wx + (cw - w), wantWy = before.wy + (ch - h);
      wantWx = Math.max(vl + M, Math.min(wantWx, vr - M - w)); wantWy = Math.max(vt + M, Math.min(wantWy, vbm - M - h));
      dbg.view = { vl, vr, vt, vbm };
      const tx = before.cx + (wantWx - before.wx) / z, ty = before.cy + (wantWy - before.wy) / z;
      try { figma.ui.reposition(tx, ty); } catch (e) { dbg.err = String(e && e.message || e); }
      await new Promise(r => setTimeout(r, 60));
      let after = await getPos(); dbg.target = { tx, ty }; dbg.after = after;
      if (after && (Math.abs(after.wx - wantWx) > 2 || Math.abs(after.wy - wantWy) > 2)) {
        const fx = tx + (wantWx - after.wx) / z, fy = ty + (wantWy - after.wy) / z;
        try { figma.ui.reposition(fx, fy); } catch (e) {} await new Promise(r => setTimeout(r, 60)); dbg.fix = { fx, fy }; dbg.final = await getPos();
      }
      figma.ui.postMessage({ type: "pos-debug", dbg });
    }
    return;
  }
  if (msg.type !== "build") return;
  if (msg.rtHash !== CACHE_HASH) { CACHE = {}; CACHE_HASH = msg.rtHash; }
  clearTimeout(exTimer);
  const S = msg.screen;
  const t0 = Date.now();
  let page = null, before = new Set();
  try {
    // page rule: a screen pinned with "page" in its JSON → that page; a screen already built somewhere → that page; otherwise the page the user is on.
    const hasTag = pg => pg.children.some(n => n.getPluginData && n.getPluginData("es-screen") === msg.name);
    if (S.PINNED_PAGE) page = await figma.getNodeByIdAsync(S.PINNED_PAGE);
    if (!page) { const cur = figma.currentPage; const known = PAGE_OF[msg.name] && await figma.getNodeByIdAsync(PAGE_OF[msg.name]); if (known && known.type === "PAGE") page = known; else if (hasTag(cur)) page = cur; else { for (const pg of figma.root.children) { if (pg === cur) continue; await pg.loadAsync(); if (hasTag(pg)) { page = pg; break; } } } if (!page) page = cur; }
    PAGE_OF[msg.name] = page.id; const T_PAGE = Date.now() - t0;
    S.PAGE_ID = page.id; S.RT_HASH = msg.rtHash;
    if (page.id !== figma.currentPage.id) await page.loadAsync(); // build in the background: never move the user to another page
    before = new Set(page.children.map(n => n.id));
    const old = page.children.filter(n => n.getPluginData("es-screen") === msg.name);
    // keep the previous frame alive during the build: the runtime reuses unchanged top-level nodes (e.g. the nav) from it, then removes it
    if (old.length) { S.POS = { x: Math.min(...old.map(o => o.x)), y: old[0].y }; S.OLD_ROOTS = old.map(o => o.id); for (const o of old) o.setPluginData("es-screen", ""); }
    let fn = null;
    if (msg.runtime) { if (RT_FN.hash !== msg.rtHash) { try { RT_FN.fn = new AF("figma", "SCREEN", "CACHE", msg.runtime); RT_FN.hash = msg.rtHash; } catch (e) { RT_FN.fn = null; } } fn = RT_FN.fn; }
    const res = fn ? await fn(figma, S, CACHE) : await runScreen(S);
    for (const id of res.roots) { const n = await figma.getNodeByIdAsync(id); if (n) n.setPluginData("es-screen", msg.name); }
    res.ms = Date.now() - t0; res.timing.page = T_PAGE; res.timing.wrapper = res.ms - res.timing.totalMs;
    figma.ui.postMessage({ type: "result", ok: true, name: msg.name, res, page: { id: page.id, name: page.name, current: figma.currentPage.id === page.id } });
    // HTML export: wait until saves go quiet, then extract once
    exTimer = setTimeout(async () => {
      try {
        const ex = msg.extract
          ? await new AF("figma", "ROOTS", "SCENE", "CACHE", msg.extract + "\\nreturn await extractDom(ROOTS, SCENE, CACHE);")(figma, res.roots, S, CACHE)
          : await extractDom(res.roots, S, CACHE);
        figma.ui.postMessage({ type: "dom", name: msg.name, scene: S, screens: ex.screens, warnings: ex.warnings });
      } catch (e) { figma.ui.postMessage({ type: "domerror", name: msg.name, error: String((e && e.message) || e) }); }
    }, 1200);
  } catch (e) {
    let error = String((e && e.message) || e);
    if (page) for (const n of [...page.children]) if (!before.has(n.id)) n.remove();
    if (/variable|style|component/i.test(error)) {
      try {
        const cols = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync();
        error += " | file: " + figma.root.name + " | libs: " + [...new Set(cols.map(c => c.libraryName))].join(", ") + " (" + cols.length + " collections)";
      } catch (e2) { error += " | file: " + figma.root.name + " | teamLibrary: " + ((e2 && e2.message) || e2); }
    }
    figma.notify("Clause: " + error.slice(0, 180), { error: true, timeout: 6000 });
    figma.ui.postMessage({ type: "result", ok: false, name: msg.name, error });
  }
};
`);

writeFileSync(resolve(dir, "ui.html"), ui);
console.error("→ figma-plugin/{manifest.json,code.js,ui.html}");
