#!/usr/bin/env node
// power-index.mjs — regenerate docs/POWER-INDEX.md: one short line per entry of docs/POWER-USE.md (bold lead phrase + line number).
// Sessions read the index (~1–2 KB) instead of the whole log (15 KB+), then `sed -n '<n>p' docs/POWER-USE.md` the entry they need.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const lines = readFileSync(resolve(root, "docs/POWER-USE.md"), "utf8").split("\n");
const out = ["# Power-use index (generated by scripts/power-index.mjs — do not edit)", "Read an entry: `sed -n '<line>p' docs/POWER-USE.md`. Add new learnings to POWER-USE.md, then run `node scripts/power-index.mjs`.", ""];
lines.forEach((l, i) => { const m = l.match(/^\s*[-#*]+\s*\*\*(.+?)\*\*|^#+\s+(.+)/); if (m) out.push(`- ${i + 1}: ${(m[1] || m[2]).replace(/[`:]+$/g, "").slice(0, 90)}`); });
writeFileSync(resolve(root, "docs/POWER-INDEX.md"), out.join("\n") + "\n");
console.log(`docs/POWER-INDEX.md: ${out.length - 3} entries, ${out.join("\n").length} bytes`);
