#!/usr/bin/env node
// tokens-css.mjs — ds/tokens/*.json (Figma exports) + ds/variable-keys.json → ds/tokens.css
// CSS custom properties are named after the Figma variable aliases, so DevTools shows the same names designers see.
//   --color-<alias>   --spacing-<name>   --radius-<name>   --width-<name>   --font-display|body|code   .ts-<style-slug>
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const vars = JSON.parse(readFileSync(resolve(root, "ds/tokens/variables.json"), "utf8"));
const keys = JSON.parse(readFileSync(resolve(root, "ds/variable-keys.json"), "utf8"));
const ts = JSON.parse(readFileSync(resolve(root, "ds/tokens/text-styles.json"), "utf8")).textStyles;

const byId = new Map(vars.variables.map(v => [v.id, v]));
const byName = new Map(vars.variables.map(v => [v.name, v]));
const colById = new Map(vars.collections.map(c => [c.id, c]));
const modeFor = (v, want) => {
  const c = colById.get(v.variableCollectionId);
  const m = c.modes.find(m => m.name === want) || c.modes.find(m => m.modeId === c.defaultModeId) || c.modes[0];
  return m.modeId;
};
function value(v, mode = "Light mode", depth = 0) {
  if (depth > 8) throw new Error("alias loop " + v.name);
  const raw = v.valuesByMode[modeFor(v, mode)];
  if (raw && raw.type === "VARIABLE_ALIAS") return value(byId.get(raw.id), mode, depth + 1);
  return raw;
}
const hex = c => {
  const h = n => Math.round(n * 255).toString(16).padStart(2, "0");
  return c.a !== undefined && c.a < 1 ? `rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${+c.a.toFixed(3)})` : `#${h(c.r)}${h(c.g)}${h(c.b)}`;
};

const lines = [];
// colors: alias → full name (via the key both maps share)
const nameByKey = Object.fromEntries(Object.entries(keys.colors).map(([n, k]) => [k, n]));
let missing = 0;
for (const [alias, key] of Object.entries(keys.colorAliases)) {
  const v = byName.get(nameByKey[key]);
  if (!v) { missing++; continue; }
  lines.push(`  --color-${alias}: ${hex(value(v))};`);
}
const num = (prefix, map) => { for (const name of Object.keys(map)) { const v = byName.get(name); if (v) lines.push(`  --${name}: ${value(v)}px;`); } };
num("spacing", keys.spacing); num("radius", keys.radius); num("width", keys.widths);
for (const [k, n] of [["font-family-display", "display"], ["font-family-body", "body"], ["font-family-code", "code"]]) {
  const v = byName.get("Font family/" + k); if (v) lines.push(`  --font-${n}: "${value(v)}", system-ui, sans-serif;`);
}

const W = { Regular: 400, Medium: 500, SemiBold: 600, "Semi Bold": 600, Bold: 700 };
const fam = f => (/spectral/i.test(f) ? "var(--font-display)" : /mono/i.test(f) ? "var(--font-code)" : "var(--font-body)");
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const classes = ts.map(s => {
  const ls = s.letterSpacing && s.letterSpacing.value ? `letter-spacing:${+(s.letterSpacing.value / 100).toFixed(4)}em;` : "";
  return `.ts-${slug(s.name)}{font-family:${fam(s.fontFamily)};font-size:${s.fontSize}px;line-height:${s.lineHeight && s.lineHeight.value ? s.lineHeight.value + "px" : "normal"};font-weight:${W[s.fontStyle] || 400};${ls}}`;
});

const css = `/* generated by scripts/tokens-css.mjs from ds/tokens (Figma Variables export, Light mode). Do not edit. */\n:root {\n${lines.join("\n")}\n}\n${classes.join("\n")}\n`;
writeFileSync(resolve(root, "ds/tokens.css"), css);
console.error(`→ ds/tokens.css (${lines.length} vars, ${classes.length} text styles${missing ? `, ${missing} colors missing from export` : ""})`);
