// generated by scripts/build-plugin.mjs — do not edit
figma.showUI(__html__, { width: 320, height: 520, visible: figma.command === "panel" || figma.command === "extract" });
figma.ui.postMessage({ type: "cmd", command: figma.command });


// Clause Assist — annotate = selection → context. Runs in code.js. Draws nothing on the canvas; stores nothing in the file.
const clScreen = n => { try { return n.getPluginData("es-screen") || null; } catch (e) { return null; } };
async function clCtx(n) {
  const o = { id: n.id, name: n.name, type: n.type, w: Math.round(n.width), h: Math.round(n.height) };
  const path = []; let p = n.parent, screen = clScreen(n), inst = n.type === "INSTANCE" ? n : null;
  while (p && p.type !== "PAGE" && p.type !== "DOCUMENT") { path.unshift(p.name); const s = clScreen(p); if (s) screen = s; if (p.type === "INSTANCE") inst = p; p = p.parent; }
  o.path = path; o.screen = screen;
  try {
    if (inst) { const mc = await inst.getMainComponentAsync(); const set = mc && mc.parent && mc.parent.type === "COMPONENT_SET" ? mc.parent : null; o.component = mc && (set ? set.name : mc.name); if (inst !== n) o.instance = { name: inst.name, id: inst.id }; o.props = {}; for (const [k, v] of Object.entries(inst.componentProperties)) o.props[k.split("#")[0]] = v.value; }
    if (n.type === "TEXT") { o.text = n.characters.slice(0, 200); const sid = n.textStyleId; if (sid && sid !== figma.mixed) { const st = await figma.getStyleByIdAsync(sid); o.textStyle = st && st.name; } }
    if ("layoutMode" in n && n.layoutMode !== "NONE") o.layout = { mode: n.layoutMode, gap: n.itemSpacing, pad: [n.paddingTop, n.paddingRight, n.paddingBottom, n.paddingLeft] };
  } catch (e) {}
  return o;
}
function clPrompt(items, file, page) {
  const L = ["Apply these " + items.length + " review comment" + (items.length === 1 ? "" : "s") + " from Figma (file: " + file + ", page: " + page + "). Read CLAUDE.md first.",
    "Rules: edit screens/<screen>.json only (a layer's name is the JSON `i` id; layers inside a component instance → `ops`). Catalog components + tokens only, exact prop names, no raw hex. Lint clean, zero rebuild warnings, verify with `node scripts/inspect.mjs <nodeId> --raw` / `--vs`.", ""];
  items.forEach((it, i) => {
    L.push((i + 1) + ". " + it.text.replace(/\s*\n\s*/g, " ") + (it.tags.length ? "  [" + it.tags.join(", ") + "]" : ""));
    for (const t of it.targets) {
      L.push("   target: " + t.name + " (" + t.type + (t.component ? " · " + t.component : "") + ") id " + t.id + " " + t.w + "×" + t.h + " · " + (t.screen ? "screen " + t.screen + " → screens/" + t.screen + ".json" : "not a Clause-built frame"));
      if (t.instance) L.push("     inside instance: " + t.instance.name + " id " + t.instance.id);
      if (t.path && t.path.length) L.push("     path: " + t.path.join(" › "));
      if (t.props && Object.keys(t.props).length) L.push("     props: " + JSON.stringify(t.props));
      if (t.text) L.push("     text: " + JSON.stringify(t.text) + (t.textStyle ? " · " + t.textStyle : ""));
      if (t.layout) L.push("     layout: " + t.layout.mode + " gap " + t.layout.gap + " pad [" + t.layout.pad + "]");
    }
  });
  return L.join("\n");
}
let selTimer = null;
async function pushSel() {
  const sel = figma.currentPage.selection.slice(0, 12), out = [];
  for (const n of sel) out.push(await clCtx(n));
  figma.ui.postMessage({ type: "sel", nodes: out, page: figma.currentPage.name, file: figma.root.name });
}
figma.on("selectionchange", () => { clearTimeout(selTimer); selTimer = setTimeout(pushSel, 120); });
figma.on("currentpagechange", pushSel);
async function annMessage(msg) {
  if (msg.type === "sel-get") { await pushSel(); return true; }
  if (msg.type === "locate") { const n = await figma.getNodeByIdAsync(msg.id); if (n) { figma.currentPage.selection = [n]; figma.viewport.scrollAndZoomIntoView([n]); } return true; }
  if (msg.type === "prompt") { figma.ui.postMessage({ type: "prompt", text: clPrompt(msg.items, figma.root.name, figma.currentPage.name), n: msg.items.length }); return true; }
  return false;
}

// Clause Assist — "Extract components": builds the whole ds/ catalog from the open file + its enabled libraries.
// Runs in code.js (and testable through use_figma). Emits parts through `emit(part, data)`; nothing is written to the file.
const dsSlug = s => String(s).split("/").pop().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "x";
const dsCut = (t, n) => { t = String(t).replace(/\s+/g, " ").trim(); return t.length > n ? t.slice(0, n - 1) + "…" : t; };
const dsProps = defs => { const o = {}; for (const [k, v] of Object.entries(defs || {})) o[k.split("#")[0]] = v.type === "VARIANT" ? v.variantOptions : v.type; return o; };
const dsVisTexts = (n, max) => n.findAll(t => t.type === "TEXT" && t.visible).slice(0, max).map(t => dsCut(t.characters, 25));
const dsNested = n => [...new Set(n.findAll(x => x.type === "INSTANCE" && x.visible).map(x => x.name))].slice(0, 6);
function dsSection(n) { for (let p = n.parent; p && p.type !== "PAGE"; p = p.parent) if (p.type === "SECTION") return p.name; return null; }
function dsUniqueKey(used, base) { let k = base, i = 2; while (used.has(k)) k = base + "-" + i++; used.add(k); return k; }

async function dsExtract(opts, emit, progress) {
  opts = opts || {}; const ignore = new Set((opts.ignoreSections || []).map(s => s.trim()).filter(Boolean));
  const say = t => { try { progress && progress(t); } catch (e) {} };
  const pages = figma.root.children; const used = new Set();
  // ---------- 1. local components (every page; sections in `ignore` are skipped)
  const local = []; const mcCache = new Map(); const libMap = new Map(); const usedStyleIds = new Set();
  for (const page of pages) {
    say("Reading page " + page.name); await page.loadAsync();
    for (const n of page.findAllWithCriteria({ types: ["COMPONENT_SET", "COMPONENT"] })) {
      if (n.type === "COMPONENT" && n.parent && n.parent.type === "COMPONENT_SET") continue;
      const sec = dsSection(n); if (sec && ignore.has(sec)) continue;
      const isSet = n.type === "COMPONENT_SET"; const main = isSet ? (n.defaultVariant || n.children[0]) : n;
      let defs = {}; try { defs = n.componentPropertyDefinitions; } catch (e) {}
      local.push({ key: dsUniqueKey(used, dsSlug(n.name)), id: n.id, name: n.name, section: sec, set: isSet, props: dsProps(defs), default: isSet ? main.name : null, size: [Math.round(main.width), Math.round(main.height)], texts: dsVisTexts(main, 6), nested: dsNested(main) });
    }
    // ---------- 2. library components = every remote main component instanced anywhere in the file
    for (const inst of page.findAllWithCriteria({ types: ["INSTANCE"] })) {
      let mc; try { mc = await inst.getMainComponentAsync(); } catch (e) { continue; }
      if (!mc || !mc.remote) continue;
      const set = mc.parent && mc.parent.type === "COMPONENT_SET" ? mc.parent : null; const id = set ? set.id : mc.id;
      if (libMap.has(id)) continue;
      let defs = {}; try { defs = set ? set.componentPropertyDefinitions : mc.componentPropertyDefinitions; } catch (e) {}
      const dv = set ? (set.defaultVariant || mc) : mc; const nm = set ? set.name : mc.name;
      const icon = !set && mc.width <= 32 && Math.abs(mc.width - mc.height) < 1 && !/\s/.test(nm.split("/").pop());
      libMap.set(id, { key: null, _base: (icon ? "icon-" : "") + dsSlug(nm), name: nm, lib: true, setKey: set ? set.key : undefined, variantKey: dv.key, variant: set ? dv.name : nm, default: set ? dv.name : null, props: dsProps(defs), texts: dsVisTexts(inst, 6) });
    }
    for (const t of page.findAllWithCriteria({ types: ["TEXT"] })) { const s = t.textStyleId; if (s && s !== figma.mixed) usedStyleIds.add(s); }
  }
  const library = [...libMap.values()].map(x => { x.key = dsUniqueKey(used, x._base); delete x._base; return x; });
  emit("components", { _source: figma.root.name + " — extracted by Clause Assist", local, library });
  say(local.length + " local + " + library.length + " library components");

  // ---------- 3. variables: local collections + every enabled library collection (imported so values/aliases resolve)
  const variables = [], collections = [], colKeyByName = {};
  const seenVar = new Set();
  const pushVar = v => { if (seenVar.has(v.id)) return; seenVar.add(v.id); variables.push({ id: v.id, name: v.name, resolvedType: v.resolvedType, key: v.key, remote: v.remote, variableCollectionId: v.variableCollectionId, valuesByMode: v.valuesByMode }); };
  const pushCol = c => { if (collections.some(x => x.id === c.id)) return; collections.push({ id: c.id, name: c.name, key: c.key, remote: c.remote, modes: c.modes, defaultModeId: c.defaultModeId }); colKeyByName[c.name] = c.key; };
  for (const c of await figma.variables.getLocalVariableCollectionsAsync()) { pushCol(c); for (const id of c.variableIds) { const v = await figma.variables.getVariableByIdAsync(id); if (v) pushVar(v); } }
  let libCols = []; try { libCols = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync(); } catch (e) { say("teamLibrary unavailable: " + e.message); }
  for (const lc of libCols) {
    say("Importing " + lc.libraryName + " / " + lc.name);
    let list = []; try { list = await figma.teamLibrary.getVariablesInLibraryCollectionAsync(lc.key); } catch (e) { continue; }
    for (const lv of list) { try { const v = await figma.variables.importVariableByKeyAsync(lv.key); pushVar(v); const c = await figma.variables.getVariableCollectionByIdAsync(v.variableCollectionId); if (c) pushCol(c); } catch (e) {} }
  }
  // resolve alias targets that were not in any enabled collection (walk until closed)
  for (let round = 0; round < 4; round++) {
    const missing = new Set();
    for (const v of variables) for (const raw of Object.values(v.valuesByMode || {})) if (raw && raw.type === "VARIABLE_ALIAS" && !seenVar.has(raw.id)) missing.add(raw.id);
    if (!missing.size) break;
    for (const id of missing) { try { const v = await figma.variables.getVariableByIdAsync(id); if (v) { pushVar(v); const c = await figma.variables.getVariableCollectionByIdAsync(v.variableCollectionId); if (c) pushCol(c); } } catch (e) {} }
  }
  emit("variables", { variables, collections, exportedAt: new Date().toISOString(), pluginVersion: "clause-extract" });

  // ---------- 4. text styles: local + every style used in the file
  const styles = new Map();
  const addStyle = s => { if (!s || styles.has(s.id)) return; styles.set(s.id, { name: s.name, key: s.key, remote: s.remote, fontFamily: s.fontName.family, fontStyle: s.fontName.style, fontSize: s.fontSize, lineHeight: s.lineHeight, letterSpacing: s.letterSpacing }); };
  for (const s of await figma.getLocalTextStylesAsync()) addStyle(s);
  for (const id of usedStyleIds) { try { addStyle(await figma.getStyleByIdAsync(id)); } catch (e) {} }
  const textStyles = [...styles.values()];
  emit("textStyles", { textStyles });

  // ---------- 5. variable-keys: the compact maps the compiler uses
  const byPrefix = p => { const o = {}; for (const v of variables) if (v.name.indexOf(p) === 0 && v.resolvedType === "FLOAT") o[v.name] = v.key; return o; };
  const colors = {}, colorAliases = {}, fonts = {};
  const colorVars = variables.filter(v => v.resolvedType === "COLOR" && !/^palette\//i.test(v.name) && !/^_/.test(v.name));
  for (const v of colorVars) { colors[v.name] = v.key; const alias = v.name.split("/").pop().replace(/\s*\(.*\)\s*$/, "").trim(); if (alias && !(alias in colorAliases)) colorAliases[alias] = v.key; }
  for (const v of variables) if (v.resolvedType === "STRING" && /font[- ]family/i.test(v.name)) fonts[v.name.split("/").pop()] = v.key;
  const tsMap = {}; for (const s of textStyles) tsMap[s.name] = s.key;
  emit("variableKeys", { _collections: colKeyByName, spacing: byPrefix("spacing-"), radius: byPrefix("radius-"), widths: byPrefix("width-"), containers: byPrefix("container-"), fonts, colors, colorAliases, textStyles: tsMap });
  emit("meta", { file: figma.root.name, fileKey: figma.fileKey || null, currentPage: { id: figma.currentPage.id, name: figma.currentPage.name }, pages: pages.map(p => ({ id: p.id, name: p.name })), ignored: [...ignore] });
  return { local: local.length, library: library.length, variables: variables.length, collections: collections.length, textStyles: textStyles.length, colors: Object.keys(colorAliases).length };
}


const AF = Object.getPrototypeOf(async function () {}).constructor;
let CACHE = {}, CACHE_HASH = null, exTimer = null; let UI_SIZE = { w: 320, h: 520 }; const PAGE_OF = {}, RT_FN = { hash: null, fn: null }; // screen name → page id (skips the all-pages walk on rebuilds)

figma.ui.onmessage = async (msg) => {
  if (await annMessage(msg)) return;
  if (msg.type === "notify") { figma.notify(msg.text, { error: !!msg.error, timeout: msg.error ? 6000 : 1500 }); return; }
  if (msg.type === "ds-extract") {
    const T0 = Date.now(); const say = t => figma.ui.postMessage({ type: "ds-progress", text: t });
    try { const r = await dsExtract({ ignoreSections: msg.ignoreSections || [] }, (part, data) => figma.ui.postMessage({ type: "ds-part", part, data }), say); figma.ui.postMessage({ type: "ds-done", result: r, ms: Date.now() - T0 }); }
    catch (e) { figma.ui.postMessage({ type: "ds-done", error: String((e && e.message) || e) }); }
    return;
  }
  if (msg.type === "resize") {
    // reposition() takes CANVAS coordinates while the window size is in screen px (measured: windowSpace = origin + zoom × canvas).
    // So: read the window position, resize (anchors top-left), then move by the size delta converted px → canvas units (÷ zoom); verify and correct once.
    const w = Math.round(msg.w), h = Math.round(msg.h), cw = UI_SIZE.w, ch = UI_SIZE.h;
    const getPos = async () => { try { const p = await figma.ui.getPosition(); return p && p.windowSpace && p.canvasSpace ? { wx: p.windowSpace.x, wy: p.windowSpace.y, cx: p.canvasSpace.x, cy: p.canvasSpace.y } : null; } catch (e) { return null; } };
    const before = msg.anchor === "br" ? await getPos() : null;
    figma.ui.resize(w, h); UI_SIZE = { w, h };
    if (before) {
      const z = figma.viewport.zoom || 1, dbg = { z, before, cw, ch, w, h };
      // anchor the bottom-right corner, then clamp the window inside the visible canvas (never over the side panels)
      const vb = figma.viewport.bounds, M = 12;
      const toWx = c => before.wx + z * (c - before.cx), toWy = c => before.wy + z * (c - before.cy);
      const vl = toWx(vb.x), vr = toWx(vb.x + vb.width), vt = toWy(vb.y), vbm = toWy(vb.y + vb.height);
      let wantWx = before.wx + (cw - w), wantWy = before.wy + (ch - h);
      wantWx = Math.max(vl + M, Math.min(wantWx, vr - M - w)); wantWy = Math.max(vt + M, Math.min(wantWy, vbm - M - h));
      dbg.view = { vl, vr, vt, vbm };
      const tx = before.cx + (wantWx - before.wx) / z, ty = before.cy + (wantWy - before.wy) / z;
      try { figma.ui.reposition(tx, ty); } catch (e) { dbg.err = String(e && e.message || e); }
      await new Promise(r => setTimeout(r, 60));
      let after = await getPos(); dbg.target = { tx, ty }; dbg.after = after;
      if (after && (Math.abs(after.wx - wantWx) > 2 || Math.abs(after.wy - wantWy) > 2)) {
        const fx = tx + (wantWx - after.wx) / z, fy = ty + (wantWy - after.wy) / z;
        try { figma.ui.reposition(fx, fy); } catch (e) {} await new Promise(r => setTimeout(r, 60)); dbg.fix = { fx, fy }; dbg.final = await getPos();
      }
      figma.ui.postMessage({ type: "pos-debug", dbg });
    }
    return;
  }
  if (msg.type !== "build") return;
  if (msg.rtHash !== CACHE_HASH) { CACHE = {}; CACHE_HASH = msg.rtHash; }
  clearTimeout(exTimer);
  const S = msg.screen;
  const t0 = Date.now();
  let page = null, before = new Set();
  try {
    // page rule: a screen pinned with "page" in its JSON → that page; a screen already built somewhere → that page; otherwise the page the user is on.
    const hasTag = pg => pg.children.some(n => n.getPluginData && n.getPluginData("es-screen") === msg.name);
    if (S.PINNED_PAGE) page = await figma.getNodeByIdAsync(S.PINNED_PAGE);
    if (!page) { const cur = figma.currentPage; const known = PAGE_OF[msg.name] && await figma.getNodeByIdAsync(PAGE_OF[msg.name]); if (known && known.type === "PAGE") page = known; else if (hasTag(cur)) page = cur; else { for (const pg of figma.root.children) { if (pg === cur) continue; await pg.loadAsync(); if (hasTag(pg)) { page = pg; break; } } } if (!page) page = cur; }
    PAGE_OF[msg.name] = page.id; const T_PAGE = Date.now() - t0;
    S.PAGE_ID = page.id; S.RT_HASH = msg.rtHash;
    await figma.setCurrentPageAsync(page);
    before = new Set(page.children.map(n => n.id));
    const old = page.children.filter(n => n.getPluginData("es-screen") === msg.name);
    // keep the previous frame alive during the build: the runtime reuses unchanged top-level nodes (e.g. the nav) from it, then removes it
    if (old.length) { S.POS = { x: Math.min(...old.map(o => o.x)), y: old[0].y }; S.OLD_ROOTS = old.map(o => o.id); for (const o of old) o.setPluginData("es-screen", ""); }
    let fn = null;
    if (msg.runtime) { if (RT_FN.hash !== msg.rtHash) { try { RT_FN.fn = new AF("figma", "SCREEN", "CACHE", msg.runtime); RT_FN.hash = msg.rtHash; } catch (e) { RT_FN.fn = null; } } fn = RT_FN.fn; }
    const res = fn ? await fn(figma, S, CACHE) : await runScreen(S);
    for (const id of res.roots) { const n = await figma.getNodeByIdAsync(id); if (n) n.setPluginData("es-screen", msg.name); }
    res.ms = Date.now() - t0; res.timing.page = T_PAGE; res.timing.wrapper = res.ms - res.timing.totalMs;
    figma.ui.postMessage({ type: "result", ok: true, name: msg.name, res });
    // HTML export: wait until saves go quiet, then extract once
    exTimer = setTimeout(async () => {
      try {
        const ex = msg.extract
          ? await new AF("figma", "ROOTS", "SCENE", "CACHE", msg.extract + "\nreturn await extractDom(ROOTS, SCENE, CACHE);")(figma, res.roots, S, CACHE)
          : await extractDom(res.roots, S, CACHE);
        figma.ui.postMessage({ type: "dom", name: msg.name, scene: S, screens: ex.screens, warnings: ex.warnings });
      } catch (e) { figma.ui.postMessage({ type: "domerror", name: msg.name, error: String((e && e.message) || e) }); }
    }, 1200);
  } catch (e) {
    let error = String((e && e.message) || e);
    if (page) for (const n of [...page.children]) if (!before.has(n.id)) n.remove();
    if (/variable|style|component/i.test(error)) {
      try {
        const cols = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync();
        error += " | file: " + figma.root.name + " | libs: " + [...new Set(cols.map(c => c.libraryName))].join(", ") + " (" + cols.length + " collections)";
      } catch (e2) { error += " | file: " + figma.root.name + " | teamLibrary: " + ((e2 && e2.message) || e2); }
    }
    figma.notify("Clause: " + error.slice(0, 180), { error: true, timeout: 6000 });
    figma.ui.postMessage({ type: "result", ok: false, name: msg.name, error });
  }
};
